language: ruby
cache: bundler
rvm:
  - 2.4.0
env:
  global:
    - CC_TEST_REPORTER_ID=b92d3200cc23b1d88a0dce55f92c7dc814c720eb3d6bfee2a9c9eed4a9ef2aee
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
  slack: navyblue-team:ioO5diAGc5WUQVDKc5BH1UbE
